###1.	Deberás utilizar el archivo llamado bank_marketing.csv. con los datos de problema.
###4.	Incluye las librerías que consideres adecuadas y carga los datos del archivo en una variable llamada “data”.

In [3]:
# Paso 1: Importar librerías y cargar datos
import pandas as pd

# Montar Google Drive si es necesario
from google.colab import drive
drive.mount('/content/drive')

# Ruta al archivo bank_marketing.csv en Google Drive
file_path = "/content/drive/MyDrive/Reto: Mercadotecnia telefónica con aprendizaje supervisado/bank_marketing.csv"

# Cargar los datos en un DataFrame
data = pd.read_csv(file_path)

# Verificar que se haya cargado correctamente
data.head()


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


age            job  marital  education default  balance housing loan  \
0   31  self-employed  married   tertiary      no     2666      no   no   
1   29     unemployed   single    unknown      no     1584      no   no   
2   41    blue-collar  married  secondary      no     2152     yes   no   
3   50    blue-collar  married  secondary      no       84     yes   no   
4   40         admin.  married  secondary      no        0      no   no   

    contact  day month  duration  campaign  pdays  previous poutcome    y  
0  cellular   10   nov       318         2     97         6  success  yes  
1  cellular    6   sep       245         1     -1         0  unknown  yes  
2  cellular   17   nov       369         1     -1         0  unknown   no  
3  cellular   17   jul        18         8     -1         0  unknown   no  
4  cellular   28   jul       496         2    182        11  success  yes

###2.	Utilizar el archivo bank-names.txt para obtener información de cada una de las variables.

In [4]:
# Paso 2: Leer y mostrar información del archivo bank-names.txt
file_path_bank_names = "/content/drive/MyDrive/Reto: Mercadotecnia telefónica con aprendizaje supervisado/bank-names.txt"

# Leer el archivo bank-names.txt
with open(file_path_bank_names, 'r') as file:
    bank_names_content = file.read()

# Mostrar el contenido del archivo
print(bank_names_content)


Citation Request:
  This dataset is public available for research. The details are described in [Moro et al., 2011]. 
  Please include this citation if you plan to use this database:

  [Moro et al., 2011] S. Moro, R. Laureano and P. Cortez. Using Data Mining for Bank Direct Marketing: An Application of the CRISP-DM Methodology. 
  In P. Novais et al. (Eds.), Proceedings of the European Simulation and Modelling Conference - ESM'2011, pp. 117-121, Guimarães, Portugal, October, 2011. EUROSIS.

  Available at: [pdf] http://hdl.handle.net/1822/14838
                [bib] http://www3.dsi.uminho.pt/pcortez/bib/2011-esm-1.txt

1. Title: Bank Marketing

2. Sources
   Created by: Paulo Cortez (Univ. Minho) and Sérgio Moro (ISCTE-IUL) @ 2012
   
3. Past Usage:

  The full dataset was described and analyzed in:

  S. Moro, R. Laureano and P. Cortez. Using Data Mining for Bank Direct Marketing: An Application of the CRISP-DM Methodology. 
  In P. Novais et al. (Eds.), Proceedings of the European

### 5.	Obtener la información de dicha base de datos que incluya el número de registros, el total de variables, el tipo de cada variable, la cantidad de datos perdidos de cada variable en caso de que existan.

In [5]:
# Número de registros
num_records = len(data)

# Total de variables
num_variables = len(data.columns)

# Tipo de cada variable
variable_types = data.dtypes

# Cantidad de datos perdidos de cada variable en caso de que existan
missing_data = data.isnull().sum()

# Mostrar la información obtenida
print("Número de registros:", num_records)
print("Total de variables:", num_variables)
print("\nTipos de variables:")
print(variable_types)
print("\nCantidad de datos perdidos de cada variable:")
print(missing_data)

# Imprimir información resumida del DataFrame
print(data.info())


Número de registros: 9000
Total de variables: 17

Tipos de variables:
age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

Cantidad de datos perdidos de cada variable:
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        9000 non-null   int64 
 1   job        9000 non-null   object

###6.	Transforma las variables categóricas de manera que puedan ser tratadas numéricamente. Justifica si utilizas LabelEncoder o OneHotEcoder.

In [6]:
# Paso 6: Transformar variables categóricas utilizando OneHotEncoder
from sklearn.preprocessing import OneHotEncoder

# Seleccionar solo las columnas categóricas
categorical_columns = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']

# Crear un objeto OneHotEncoder
onehot_encoder = OneHotEncoder(sparse=False, drop='first')

# Aplicar OneHotEncoder a las columnas categóricas y combinar los resultados con el DataFrame original
encoded_data = pd.concat([data.drop(columns=categorical_columns),
                          pd.DataFrame(onehot_encoder.fit_transform(data[categorical_columns])),
                         ], axis=1)

# Mostrar las primeras filas del DataFrame transformado
print(encoded_data.head())


   age  balance  day  duration  campaign  pdays  previous    y    0    1  ...  \
0   31     2666   10       318         2     97         6  yes  0.0  0.0  ...   
1   29     1584    6       245         1     -1         0  yes  0.0  0.0  ...   
2   41     2152   17       369         1     -1         0   no  1.0  0.0  ...   
3   50       84   17        18         8     -1         0   no  1.0  0.0  ...   
4   40        0   28       496         2    182        11  yes  0.0  0.0  ...   

    25   26   27   28   29   30   31   32   33   34  
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  
2  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  
3  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
4  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  

[5 rows x 43 columns]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


### 7.	Transforma las variables numéricas en los casos que se tenga algún tipo de sesgo.

In [7]:
# Importar librerías necesarias
import numpy as np

# Lista de variables numéricas
numeric_columns = ['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']

# Aplicar la transformación logarítmica a las variables numéricas con sesgo
for column in numeric_columns:
    if data[column].min() <= 0:  # Verificar si hay valores no permitidos para la transformación logarítmica
        data[column] = np.log(data[column] - data[column].min() + 1)  # Aplicar la transformación logarítmica
    else:
        data[column] = np.log(data[column])  # Aplicar la transformación logarítmica

# Mostrar las primeras filas del DataFrame transformado
print(data.head())


        age            job  marital  education default   balance housing loan  \
0  3.433987  self-employed  married   tertiary      no  8.652598      no   no   
1  3.367296     unemployed   single    unknown      no  8.443116      no   no   
2  3.713572    blue-collar  married  secondary      no  8.558527     yes   no   
3  3.912023    blue-collar  married  secondary      no  8.052933     yes   no   
4  3.688879         admin.  married  secondary      no  8.025843      no   no   

    contact       day month  duration  campaign     pdays  previous poutcome  \
0  cellular  2.302585   nov  5.762051  0.693147  4.595120  1.945910  success   
1  cellular  1.791759   sep  5.501258  0.000000  0.000000  0.000000  unknown   
2  cellular  2.833213   nov  5.910797  0.000000  0.000000  0.000000  unknown   
3  cellular  2.833213   jul  2.890372  2.079442  0.000000  0.000000  unknown   
4  cellular  3.332205   jul  6.206576  0.693147  5.214936  2.484907  success   

     y  
0  yes  
1  yes  
2   n

### 8.	Considera la variable “y” como la variable de salida y el resto de las variables como las variables de entrada.

In [8]:
# Separar las variables de entrada (features) y la variable de salida (target)
X = data.drop(columns=['y'])  # Features (variables de entrada)
y = data['y']                 # Target (variable de salida)

# Mostrar las primeras filas de las variables de entrada y salida
print("Variables de entrada (features):")
print(X.head())
print("\nVariable de salida (target):")
print(y.head())


Variables de entrada (features):
        age            job  marital  education default   balance housing loan  \
0  3.433987  self-employed  married   tertiary      no  8.652598      no   no   
1  3.367296     unemployed   single    unknown      no  8.443116      no   no   
2  3.713572    blue-collar  married  secondary      no  8.558527     yes   no   
3  3.912023    blue-collar  married  secondary      no  8.052933     yes   no   
4  3.688879         admin.  married  secondary      no  8.025843      no   no   

    contact       day month  duration  campaign     pdays  previous poutcome  
0  cellular  2.302585   nov  5.762051  0.693147  4.595120  1.945910  success  
1  cellular  1.791759   sep  5.501258  0.000000  0.000000  0.000000  unknown  
2  cellular  2.833213   nov  5.910797  0.000000  0.000000  0.000000  unknown  
3  cellular  2.833213   jul  2.890372  2.079442  0.000000  0.000000  unknown  
4  cellular  3.332205   jul  6.206576  0.693147  5.214936  2.484907  success  

Varia

###9.	Particiona los datos en los conjuntos de entrenamiento, validación y prueba en 60%, 20% y 20%, respectivamente.

In [9]:
# Importar librerías necesarias
from sklearn.model_selection import train_test_split

# Primero, dividimos los datos en conjunto de entrenamiento y conjunto de prueba (80% entrenamiento, 20% prueba)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Luego, dividimos el conjunto de entrenamiento en conjunto de entrenamiento y conjunto de validación (75% entrenamiento, 25% validación)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=42)

# Mostramos las formas de los conjuntos resultantes
print("Forma del conjunto de entrenamiento:", X_train.shape, y_train.shape) #Contiene 5400 muestras y 16 características.
print("Forma del conjunto de validación:", X_val.shape, y_val.shape)
print("Forma del conjunto de prueba:", X_test.shape, y_test.shape)


Forma del conjunto de entrenamiento: (5400, 16) (5400,)
Forma del conjunto de validación: (1800, 16) (1800,)
Forma del conjunto de prueba: (1800, 16) (1800,)


### 10.	Aplica el modelo Regresión Logística en el conjunto de entrenamiento. Valida el modelo con las predicciones del conjunto de validación y su matriz de confusión. Ajusta los parámetros del modelo hasta obtener tu mejor resultado.

In [10]:
# Importar librerías necesarias
# Esta librería permite aplicar transformaciones específicas a diferentes columnas del conjunto de datos.
# Se utiliza para aplicar diferentes transformaciones a las características categóricas y numéricas por separado.
from sklearn.compose import ColumnTransformer
# Esta librería se utiliza para convertir características categóricas en representaciones numéricas utilizando codificación one-hot.
# Crea una columna binaria para cada categoría en la característica original.
from sklearn.preprocessing import OneHotEncoder
# Esta librería se utiliza para encadenar múltiples pasos de procesamiento de datos juntos, como transformaciones y modelos, en un solo objeto.
# Facilita la construcción y el ajuste de modelos con pasos de preprocesamiento complejos.
from sklearn.pipeline import Pipeline
# Esta librería implementa el modelo de regresión logística, que es un algoritmo de aprendizaje supervisado utilizado para la clasificación binaria.
# Ajusta los parámetros del modelo para predecir la probabilidad de pertenecer a una clase.
from sklearn.linear_model import LogisticRegression
# confusion_matrix: Esta librería calcula la matriz de confusión, que es una tabla que describe el rendimiento de un modelo de clasificación
# en un conjunto de datos de prueba. Ayuda a evaluar el desempeño del modelo al comparar las predicciones con los valores reales.
# accuracy_score: Esta librería calcula la precisión, que es una métrica que mide la fracción de predicciones correctas realizadas por el modelo
# en un conjunto de datos de prueba. Es una medida comúnmente utilizada para evaluar el rendimiento de los modelos de clasificación.
from sklearn.metrics import confusion_matrix, accuracy_score


# Lista de características categóricas
categorical_features = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']

# Pipeline para transformaciones específicas en características categóricas
categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# ColumnTransformer para aplicar transformaciones a las características categóricas
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical_features)# Utilizar OneHotEncoder para convertir variables categóricas en codificación one-hot
    ])

# Construir el pipeline del modelo que incluye preprocesamiento y clasificador
model_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor), # Aplicar preprocesamiento definido anteriormente
    ('classifier', LogisticRegression(random_state=42)) # Utilizar el clasificador de Regresión Logística
])

# Entrenar el modelo en el conjunto de entrenamiento
model_pipeline.fit(X_train, y_train)

# Hacer predicciones en el conjunto de validación
y_pred_val = model_pipeline.predict(X_val)

# Calcular la matriz de confusión
conf_matrix = confusion_matrix(y_val, y_pred_val)
print("Matriz de Confusión en el conjunto de validación:")
print(conf_matrix)

# Calcular la precisión del modelo en el conjunto de validación
accuracy = accuracy_score(y_val, y_pred_val)
print("Precisión del modelo en el conjunto de validación:", accuracy)



Matriz de Confusión en el conjunto de validación:
[[934 101]
 [418 347]]
Precisión del modelo en el conjunto de validación: 0.7116666666666667


Indica el valor óptimo del parámetro de regularización C encontrado mediante la búsqueda en cuadrícula. En este caso, el valor óptimo de C es 0.1 para el modelo de regresión logística

Matriz de Confusión del mejor modelo en el conjunto de validación: La matriz de confusión muestra la distribución de las predicciones realizadas por el mejor modelo en el conjunto de validación. Esta matriz tiene cuatro elementos:

Verdaderos positivos (TP): 931
Falsos positivos (FP): 104
Verdaderos negativos (TN): 355
Falsos negativos (FN): 410

In [16]:
from sklearn.model_selection import GridSearchCV

# Definir los parámetros a explorar en la búsqueda en cuadrícula
param_grid = {'classifier__C': [0.001, 0.01, 0.1, 1, 10, 100]}

# Inicializar el objeto GridSearchCV
grid_search = GridSearchCV(model_pipeline, param_grid, cv=5, scoring='accuracy')

# Realizar la búsqueda en cuadrícula en el conjunto de entrenamiento
grid_search.fit(X_train, y_train)

# Mostrar el mejor valor de C encontrado por la búsqueda en cuadrícula
print("Mejor valor de C encontrado por la búsqueda en cuadrícula:", grid_search.best_params_)

# Obtener el mejor modelo encontrado por la búsqueda en cuadrícula
best_model = grid_search.best_estimator_

# Hacer predicciones en el conjunto de validación utilizando el mejor modelo
y_pred_val_best = best_model.predict(X_val)

# Calcular la matriz de confusión y la precisión del mejor modelo en el conjunto de validación
conf_matrix_best = confusion_matrix(y_val, y_pred_val_best) # Calcular la matriz de confusión del mejor modelo en el conjunto de validación
accuracy_best = accuracy_score(y_val, y_pred_val_best) # Calcular la precisión del mejor modelo en el conjunto de validación

print("Matriz de Confusión del mejor modelo en el conjunto de validación:")
print(conf_matrix_best)
print("Precisión del mejor modelo en el conjunto de validación:", accuracy_best)


Mejor valor de C encontrado por la búsqueda en cuadrícula: {'classifier__C': 0.1}
Matriz de Confusión del mejor modelo en el conjunto de validación:
[[931 104]
 [410 355]]
Precisión del mejor modelo en el conjunto de validación: 0.7144444444444444


In [12]:
from sklearn.model_selection import GridSearchCV

# Definir un rango más amplio de valores de C
param_grid = {'classifier__C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]}

# Inicializar el objeto GridSearchCV
grid_search = GridSearchCV(model_pipeline, param_grid, cv=5, scoring='accuracy')

# Realizar la búsqueda en cuadrícula en el conjunto de entrenamiento
grid_search.fit(X_train, y_train)

# Mostrar el mejor valor de C encontrado por la búsqueda en cuadrícula
print("Mejor valor de C encontrado por la búsqueda en cuadrícula:", grid_search.best_params_)

# Obtener el mejor modelo encontrado por la búsqueda en cuadrícula
best_model = grid_search.best_estimator_

# Hacer predicciones en el conjunto de validación utilizando el mejor modelo
y_pred_val_best = best_model.predict(X_val)

# Calcular la matriz de confusión y la precisión del mejor modelo en el conjunto de validación
conf_matrix_best = confusion_matrix(y_val, y_pred_val_best)
accuracy_best = accuracy_score(y_val, y_pred_val_best)

print("Matriz de Confusión del mejor modelo en el conjunto de validación:")
print(conf_matrix_best)
print("Precisión del mejor modelo en el conjunto de validación:", accuracy_best)


Mejor valor de C encontrado por la búsqueda en cuadrícula: {'classifier__C': 0.1}
Matriz de Confusión del mejor modelo en el conjunto de validación:
[[931 104]
 [410 355]]
Precisión del mejor modelo en el conjunto de validación: 0.7144444444444444


In [13]:
from sklearn.model_selection import GridSearchCV

# Definir los parámetros a explorar en la búsqueda en cuadrícula
param_grid = {'classifier__C': [0.001, 0.01, 0.1, 1, 10, 100],
              'classifier__penalty': ['l1', 'l2']}

# Inicializar el objeto GridSearchCV
grid_search = GridSearchCV(model_pipeline, param_grid, cv=5, scoring='accuracy')

# Realizar la búsqueda en cuadrícula en el conjunto de entrenamiento
grid_search.fit(X_train, y_train)

# Mostrar los mejores parámetros encontrados por la búsqueda en cuadrícula
print("Mejores parámetros encontrados por la búsqueda en cuadrícula:", grid_search.best_params_)

# Obtener el mejor modelo encontrado por la búsqueda en cuadrícula
best_model = grid_search.best_estimator_

# Hacer predicciones en el conjunto de validación utilizando el mejor modelo
y_pred_val_best = best_model.predict(X_val)

# Calcular la matriz de confusión y la precisión del mejor modelo en el conjunto de validación
conf_matrix_best = confusion_matrix(y_val, y_pred_val_best)
accuracy_best = accuracy_score(y_val, y_pred_val_best)

print("Matriz de Confusión del mejor modelo en el conjunto de validación:")
print(conf_matrix_best)
print("Precisión del mejor modelo en el conjunto de validación:", accuracy_best)


Mejores parámetros encontrados por la búsqueda en cuadrícula: {'classifier__C': 0.1, 'classifier__penalty': 'l2'}
Matriz de Confusión del mejor modelo en el conjunto de validación:
[[931 104]
 [410 355]]
Precisión del mejor modelo en el conjunto de validación: 0.7144444444444444


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning: 
30 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/pipeline.py", line 405, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
 

### 11.	Aplica el modelo Red Neuronal en el conjunto de entrenamiento. Valida el modelo con las predicciones del conjunto de validación y su matriz de confusión. Ajusta los parámetros del modelo hasta obtener tu mejor modelo, entre ellos el número de neuronas y capas ocultas.

In [14]:
from sklearn.preprocessing import OneHotEncoder # Importar la clase OneHotEncoder para codificar variables categóricas
from sklearn.compose import ColumnTransformer # Importar la clase ColumnTransformer para aplicar transformaciones a columnas específicas
from sklearn.neural_network import MLPClassifier # Importar la clase MLPClassifier para definir el modelo de Red Neuronal

# Definir el modelo de Red Neuronal
neural_network_model = MLPClassifier(random_state=42) # Crear una instancia del clasificador MLPClassifier con semilla aleatoria

# Definir las columnas categóricas
categorical_cols = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']

# Definir el preprocesamiento para las variables categóricas
preprocessor = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(), categorical_cols), # Aplicar codificación OneHot a las columnas categóricas
    ],
    remainder='passthrough' # Mantener las columnas no transformadas
)

# Aplicar el preprocesamiento a tus datos
X_train_encoded = preprocessor.fit_transform(X_train) # Ajustar y transformar los datos de entrenamiento
X_val_encoded = preprocessor.transform(X_val)   # Transformar los datos de validación

# Ahora puedes entrenar tu modelo de Red Neuronal con los datos codificados
neural_network_model.fit(X_train_encoded, y_train) # Entrenar el modelo con los datos de entrenamiento codificados

# Hacer predicciones en el conjunto de validación
y_pred_val_nn = neural_network_model.predict(X_val_encoded) # Realizar predicciones en los datos de validación codificados

# Calcular la matriz de confusión
conf_matrix_nn = confusion_matrix(y_val, y_pred_val_nn)
print("Matriz de Confusión en el conjunto de validación:")
print(conf_matrix_nn)

# Calcular la precisión del modelo en el conjunto de validación
accuracy_nn = accuracy_score(y_val, y_pred_val_nn)
print("Precisión del modelo en el conjunto de validación:", accuracy_nn)



Matriz de Confusión en el conjunto de validación:
[[858 177]
 [108 657]]
Precisión del modelo en el conjunto de validación: 0.8416666666666667


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


# 12.	Selecciona el mejor modelo encontrado en los incisos anteriores y utiliza el conjunto de prueba para obtener el desempeño final del modelo y su matriz de confusión.

In [15]:
# Definir el mejor modelo de Regresión Logística utilizando el resultado de la búsqueda en cuadrícula
best_model_lr = grid_search.best_estimator_

# Hacer predicciones en el conjunto de prueba utilizando el mejor modelo de Regresión Logística
y_pred_lr_test = best_model_lr.predict(X_test)

# Calcular la precisión y la matriz de confusión para el modelo de Regresión Logística
accuracy_lr_test = accuracy_score(y_test, y_pred_lr_test)  # Calcular la precisión del modelo de Regresión Logística
conf_matrix_lr_test = confusion_matrix(y_test, y_pred_lr_test) # Calcular la matriz de confusión del modelo de Regresión Logística

# Mostrar resultados
print("Desempeño del mejor modelo de Regresión Logística en el conjunto de prueba:")
print("Precisión:", accuracy_lr_test)
print("Matriz de Confusión:")
print(conf_matrix_lr_test)

# Hacer predicciones en el conjunto de prueba utilizando el mejor modelo de Red Neuronal
X_test_encoded = preprocessor.transform(X_test) # Codificar el conjunto de prueba
y_pred_nn_test = neural_network_model.predict(X_test_encoded) # Realizar predicciones en el conjunto de prueba utilizando el mejor modelo de Red Neuronal

# Calcular la precisión y la matriz de confusión para el modelo de Red Neuronal
accuracy_nn_test = accuracy_score(y_test, y_pred_nn_test)  # Calcular la precisión del modelo de Red Neuronal
conf_matrix_nn_test = confusion_matrix(y_test, y_pred_nn_test) # Calcular la matriz de confusión del modelo de Red Neuronal


# Mostrar resultados
print("\nDesempeño del mejor modelo de Red Neuronal en el conjunto de prueba:")
print("Precisión:", accuracy_nn_test)
print("Matriz de Confusión:")
print(conf_matrix_nn_test)



Desempeño del mejor modelo de Regresión Logística en el conjunto de prueba:
Precisión: 0.725
Matriz de Confusión:
[[945  70]
 [425 360]]

Desempeño del mejor modelo de Red Neuronal en el conjunto de prueba:
Precisión: 0.8466666666666667
Matriz de Confusión:
[[856 159]
 [117 668]]
